version: '3.8'

services:
  customer-support-ai:
    build: .
    ports:
      - "8501:8501"
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

volumes:
  ollama_data:
